// AUTH
export const LOADING = 'LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'

export const AUTH_ERROR = 'AUTH_ERROR'
export const USER_LOADED = 'USER_LOADED'

export const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS'
export const RESET_PASS_FAIL = 'RESET_PASS_FAIL'

export const LOGOUT = 'LOGOUT'

export const RESET = 'RESET'

// SETTING
export const LOADING_SETTING = 'LOADING_SETTING'
export const RESET_SETTING = 'RESET_SETTING'
export const SETTING_LIGHT_SUCCESS = 'SETTING_LIGHT_SUCCESS'
export const SETTING_LIGHT_FAIL = 'SETTING_LIGHT_FAIL'